[project]
name = "error-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "huggingface>=0.0.1",
    "type-enforced>=2.3.0",
    "wandb>=0.25.0",
]
